#!/bin/bash

nums=(3.14 2.718 0.57721 4.6692)
echo "PI: ${nums[0]}"

nums[4]=1.618
echo "GR: ${nums[4]}"

nums+=(1 7)

for i in ${nums[*]}; do
	echo $i
done


for i in ${nums[@]}; do
	echo $i
done

echo "Array Length: ${#nums[@]}"
echo "Idx 3 Length: ${#nums[3]}"

srt=($(for i in "${nums[@]}"; do
	echo $i;
done | sort))

unset 'srt[1]'
unset srt


