#!/bin/sh
num="$1"

case $num in
    1)
        disps=(5902)
        ;;
    2)
        disps=(5902 5903)
        ;;
    3)
        disps=(5902 5903 5904)
        ;;
    *)
        echo "Enter only 1 - 3"
        exit;
        ;;
esac

echo "megakill ssh | $num"

for (( i = 0; i < "$num"; i = i + 1 )); do
    echo "vncsetup ${disps[$i]} &"
done

sleep 0 ;

for (( i=0; i <"$num"; i=i+1 )); do
    echo "vnc2me ${disps[$i]} &"
done
