# client_secret information
spotify_token   = "BQDY-6ZfLfE8BDTIBBWFXpRUxrLCbs-QrllBuee1aorldxxxCrTnd73Tus3aZSpT1Z_3JPCqqddzAUrV4Dwlm8CBRRyDHibrgl2VgIDQ7qkoouQ5uORQ8xmGjYf-PuAZ0el9VwM4EhfxwzaP4NtF6jiJujncgBfziaoGiQCCANuWIba1VaWkITwSLL0UI11rlEXBl0HtMVE"
spotify_user_id = "ianio_one"
